/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nmr_libtess2_android_libtess2 */

#ifndef _Included_nmr_libtess2_android_libtess2
#define _Included_nmr_libtess2_android_libtess2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nmr_libtess2_android_libtess2
 * Method:    _tessNewTess
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_nmr_libtess2_1android_libtess2__1tessNewTess
  (JNIEnv *, jclass);

/*
 * Class:     nmr_libtess2_android_libtess2
 * Method:    _tessDeleteTess
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_nmr_libtess2_1android_libtess2__1tessDeleteTess
  (JNIEnv *, jclass, jlong);

/*
 * Class:     nmr_libtess2_android_libtess2
 * Method:    tessAddContour
 * Signature: (Lnmr/libtess2_android/libtess2/TESStesselator;I[FIII)V
 */
JNIEXPORT void JNICALL Java_nmr_libtess2_1android_libtess2_tessAddContour
  (JNIEnv *, jclass, jobject, jint, jfloatArray, jint, jint, jint);

/*
 * Class:     nmr_libtess2_android_libtess2
 * Method:    tessTesselate
 * Signature: (Lnmr/libtess2_android/libtess2/TESStesselator;IIII[F)I
 */
JNIEXPORT jint JNICALL Java_nmr_libtess2_1android_libtess2_tessTesselate
  (JNIEnv *, jclass, jobject, jint, jint, jint, jint, jfloatArray);

/*
 * Class:     nmr_libtess2_android_libtess2
 * Method:    tessGetVertexCount
 * Signature: (Lnmr/libtess2_android/libtess2/TESStesselator;)I
 */
JNIEXPORT jint JNICALL Java_nmr_libtess2_1android_libtess2_tessGetVertexCount
  (JNIEnv *, jclass, jobject);

/*
 * Class:     nmr_libtess2_android_libtess2
 * Method:    tessGetVertices
 * Signature: (Lnmr/libtess2_android/libtess2/TESStesselator;)[F
 */
JNIEXPORT jfloatArray JNICALL Java_nmr_libtess2_1android_libtess2_tessGetVertices
  (JNIEnv *, jclass, jobject);

/*
 * Class:     nmr_libtess2_android_libtess2
 * Method:    tessGetVertexIndices
 * Signature: (Lnmr/libtess2_android/libtess2/TESStesselator;)[I
 */
JNIEXPORT jintArray JNICALL Java_nmr_libtess2_1android_libtess2_tessGetVertexIndices
  (JNIEnv *, jclass, jobject);

/*
 * Class:     nmr_libtess2_android_libtess2
 * Method:    tessGetElementCount
 * Signature: (Lnmr/libtess2_android/libtess2/TESStesselator;)I
 */
JNIEXPORT jint JNICALL Java_nmr_libtess2_1android_libtess2_tessGetElementCount
  (JNIEnv *, jclass, jobject);

/*
 * Class:     nmr_libtess2_android_libtess2
 * Method:    tessGetElements
 * Signature: (Lnmr/libtess2_android/libtess2/TESStesselator;)[I
 */
JNIEXPORT jintArray JNICALL Java_nmr_libtess2_1android_libtess2_tessGetElements
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
